import RenderCrypto from "../_components/RenderCrypto";

export const metadata = {
  title: "Cartman / cryptos",
  description: "Generated by create next app",
};

export default async function Cryptos() {
  const res = await fetch(
    `https://min-api.cryptocompare.com/data/top/mktcapfull?limit=100&tsym=USD&api_key=897e0c0c4a8136b141a844d8318aa3893b87586360fb9bc567305444c61206fa'`
  );
  const data = await res.json();
  const crypto = data.Data;
  const { CoinInfo, DISPLAY } = crypto;

  return (
    <div className="w-full">
      {crypto.map((el) => (
        <RenderCrypto crypto={el} key={el.CoinInfo.Name} />
      ))}
    </div>
  );
}
